activity/activity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

activity/todolist/urls.py
from django.urls import path
from . import views

# Syntax
# path(route, view, name)

app_name = 'todolist'

urlpatterns = [
	path('', views.index, name='index'), 
	#/todolist/<todoitem_id> 
	#/todolist/1
	# The <int:todoitem_id> allows for creating a dynamic link where the todoitem_id is provided
	# /todolist/register
	path('register', views.register, name='register'),
	path('change_password', views.change_password, name="change_password"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_task', views.add_task, name="add_task"),
	path('<int:todoitem_id>/', views.todoitem, name="viewtodoitem"),
	path('<int:todoitem_id>/edit', views.update_task, name="update_task"),
	path('<int:todoitem_id>/delete', views.delete_task, name="delete_task"),
	path('add_event', views.add_event, name="add_event"),
	path('event/<int:event_id>/', views.event_item, name="vieweventitem"),
	path('update_profile', views.update_profile, name="update_profile"),
	# path('<int:event_id>/edit', views.update_event, name="update_event"),
	# path('<int:event_id>/delete', views.delete_event, name="delete_event"),
]

activity/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")
 
class Event(models.Model):
    event_name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=50, default="pending")
    date_created = models.DateTimeField('date created')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    

activity/todolist/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=20)
    password = forms.CharField(label="Password", max_length=20)

class RegisterForm(forms.Form):
    username = forms.CharField(label="Username", max_length=20)
    first_name = forms.CharField(label="First Name", max_length=20)
    last_name = forms.CharField(label="Last Name", max_length=20)
    email = forms.CharField(label="Email", max_length=30)
    password = forms.CharField(label="Password", max_length=20)
    confirm_password = forms.CharField(label="Confirm Password", max_length=20)

class AddTaskForm(forms.Form):
    task_name = forms.CharField(label="Task Name", max_length=50)
    description = forms.CharField(label="Description", max_length=200)
    
class UpdateTaskForm(forms.Form):
    task_name = forms.CharField(label="Task Name", max_length=50)
    description = forms.CharField(label="Description", max_length=200)
    status = forms.CharField(label="Status", max_length=50)
    
class EventForm(forms.Form):
    event_name = forms.CharField(label="Event Name", max_length=50)
    description = forms.CharField(label="Description", max_length=200)

class UpdateUserForm(forms.Form):
    first_name = forms.CharField(label="First Name", max_length=20)
    last_name = forms.CharField(label="Last Name", max_length=20)
    password = forms.CharField(label="Password", max_length=20)
    

activity/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.forms.models import model_to_dict
from django.utils import timezone

from .models import ToDoItem, Event
from .forms import EventForm, LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm, UpdateUserForm

def index(request):
	# todoitem_list = ToDoItem.objects.all()
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	event_list = Event.objects.filter(user_id=request.user.id)
	context = {
		'todoitem_list': todoitem_list,
  		'event_list': event_list,
		'user': request.user
		}

	return render(request, "todolist/index.html", context)

	# template = loader.get_template("todolist/index.html")
	# context = {
	# 	'todoitem_list': todoitem_list
	# }
	# return HttpResponse(template.render(context, request))

	# output = ', '.join([todoitem.task_name for todoitem in todoitem_list])
	# return HttpResponse(output)
	# return HttpResponse("Hello from the views.py file")

def todoitem(request, todoitem_id):
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

def register(request):
    context = {}
    
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid() == False:
            form = RegisterForm()
        else:
            username = form.cleaned_data["username"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            # confirm_password = form.cleaned_data["confirm_password"]
            
            duplicates = User.objects.filter(username=username)
            
            if not duplicates:
                user = User.objects.create(
                    username=username, 
                    first_name=first_name, 
                    last_name=last_name,
                    email=email,
                    password=make_password(password)
                )
                
                return redirect("todolist:login")
            else:
                context = {
					"error": True
				}
            
    return render(request, "todolist/register.html", context)

def change_password(request):
	is_user_authenticated = False

	user = authenticate(username="johndoe", password="johndoe1")
	print(user)

	if user is not None:
		# user = User.objects.get(username='johndoe')
		# user.set_password("johndoe1")
		# user.save()
		# is_user_authenticated = True
		authenticated_user = User.objects.get(username='johndoe')
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		is_user_authenticated = True

	context = {
		"is_user_authenticated": is_user_authenticated
	}

	return render(request, "todolist/change_password.html", context)

def login_view(request):
	context = {}
 
	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid() == False:
			form = LoginForm()
		else:
			username = form.cleaned_data["username"]
			password = form.cleaned_data["password"]
			user = authenticate(username=username, password=password)
			context = {
				"username": username,
				"password": password,
			}
			if user is not None:
				login(request, user)
				return redirect("todolist:index")
			else:
				context = {
					"error": True
				}
	return render(request, "todolist/login.html", context)
				
def logout_view(request):
	logout(request)
	return redirect("todolist:index")

def add_task(request):
    context = {}
    
    if request.method == "POST":
        
        form = AddTaskForm(request.POST)
        
        if form.is_valid() == False:
            form == AddTaskForm()
            
        else:
            task_name = form.cleaned_data["task_name"]
            description = form.cleaned_data["description"]
            duplicates = ToDoItem.objects.filter(task_name=task_name)
            
            if not duplicates:
                ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)
                return redirect("todolist:index")
            else:
                context = {
					"error": True
				}
      		
    return render(request, "todolist/add_task.html", context)

def update_task(request, todoitem_id):
    todoitem = ToDoItem.objects.filter(pk=todoitem_id)
    
    context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status,
	}    
    
    if request.method == "POST":
        form = UpdateTaskForm(request.POST)
        
        if form.is_valid() == False:
            form = UpdateTaskForm()
        else:
            task_name = form.cleaned_data["task_name"]
            description = form.cleaned_data["description"]
            status = form.cleaned_data["status"]
            
            if todoitem:
                todoitem[0].task_name = task_name
                todoitem[0].description = description
                todoitem[0].status = status
                todoitem[0].save()
                return redirect("todolist:index")
            else:
                context = {
					"error": True
				}
                
    render(request, "todolist/update_task.html", context)
    
def delete_task(request, todoitem_id):
    todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
    return redirect("todolist:index")

def event_item(request, event_id):
	event = get_object_or_404(Event, pk=event_id)
	return render(request, "todolist/event.html", model_to_dict(event))

def add_event(request):
    context = {}
    
    if request.method == "POST":
        
        form = EventForm(request.POST)
        
        if form.is_valid() == False:
            form == EventForm()
            
        else:
            event_name = form.cleaned_data["event_name"]
            description = form.cleaned_data["description"]
            duplicates = Event.objects.filter(event_name=event_name)
            
            if not duplicates:
                Event.objects.create(event_name=event_name, description=description, date_created=timezone.now(), user_id=request.user.id)
                return redirect("todolist:index")
            else:
                context = {
					"error": True
				}
      		
    return render(request, "todolist/add_event.html", context)

def update_profile(request):
    user = request.user
    # user = User.objects.filter(pk=user_id)
    
    context = {
		"user": request.user,
		"first_name": user.first_name,
		"last_name": user.first_name,
		"password": "",
	}    
    
    if request.method == "POST":
        form = UpdateUserForm(request.POST)
        if form.is_valid() == False:
            form = UpdateUserForm()
        else:
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            password = form.cleaned_data["password"]
            user = User.objects.filter(pk=user.id)
            
            if user:
                user[0].first_name = first_name
                user[0].last_name = last_name
                user[0].set_password(password)
                user[0].save()
                return redirect("todolist:index")
            else:
                context = {
					"error": True
				}
                
    return render(request, "todolist/update_profile.html", context)
  

activity/todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <h1 class="text-center my-3">Add An Event</h1>
                {% if error == True %}
                    <p class="text-danger">Duplicate event found</p>
                {% endif %}

                <form action="{% url 'todolist:add_event' %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="event_name">Event Name:</label>
                        <input type="text" class="form-control" id="event_name" name="event_name" value="{{ event_name }}" maxlength="50" required>
                    </div>
    
                    <div class="mb-3">
                        <label for="description">Description</label>
                        <textarea type="text" class="form-control" id="description" name="description" value="{{ description }}" required></textarea>
                    </div>
                    
                    <div class="text-center">
                        <input type="submit" value="Add Task" class="btn btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

activity/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <h1 class="text-center my-3">Add A Task</h1>
                {% if error == True %}
                    <p class="text-danger">Duplicate task found</p>
                {% endif %}

                <form action="{% url 'todolist:add_task' %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="task_name">Task Name:</label>
                        <input type="text" class="form-control" id="task_name" name="task_name" value="{{ task_name }}" maxlength="50" required>
                    </div>
    
                    <div class="mb-3">
                        <label for="description">Description</label>
                        <textarea type="text" class="form-control" id="description" name="description" value="{{ description }}" required></textarea>
                    </div>
                    
                    <div class="text-center">
                        <input type="submit" value="Add Task" class="btn btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

activity/todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password is correct.</p>

{% else %}
	<h1>User Password Successfully Updated!</h1>
	<p>The password has been successfully updated.</p>

{% endif %}

activity/todolist/templates/todolist/event.html
{% extends 'base.html' %}

{% block title %}Event Item{% endblock %}

{% block content%}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3 text-center">
            <h1 class="my-3">{{event_name}}</h1>
            <h3>Description</h3>
            <p>{{description}}</p>
            <h3>Status</h3>
            <p>{{status}}</p>
            <a class="btn btn-warning text-white" href="{% url 'todolist:index' %}">Back to Events</a>
        </div>
    </div>
</div>
{% endblock %}

activity/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock%}

{% block content %}
	{% if todoitem_list %}
		<h1 class="text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>
		<div class="container">
			<div class="row">
				<h3 class="text-center mb-3">My Tasks</h3>
				<ul class="list-group col-lg-2 offset-lg-5 text-center">
				{% for todoitem in todoitem_list %}
					<li class="list-group-item">
						<a class="text-decoration-none" href="{% url 'todolist:viewtodoitem' todoitem.id %}">{{todoitem.task_name}}</a>
					</li>
				{% endfor %}
				</ul> 
			</div>

			<div class="row mt-3"> 
				<h3 class="text-center mb-3">My Events</h3>
				<ul class="list-group col-lg-2 offset-lg-5 text-center">
				{% for event in event_list %}
					<li class="list-group-item">
						<a class="text-decoration-none" href="{% url 'todolist:vieweventitem' event.id %}">{{event.event_name}}</a>
					</li>
				{% empty %}
					<p>No events have been created.</p>
				{% endfor %}
				</ul>
			</div>
		</div>
	{% elif todoitem_list.count == 0 and user %}
		<p>No tasks have been created.</p>

	{% elif user.is_anonymous == True %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% else %}
		<p>No tasks have been created.</p>
	{% endif %}
{% endblock %}

activity/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Login</h1>
			{% if error == True %}
			<p class="text-danger">Invalid user credentials, pleasse check your username and password</p>
			{% endif %}

			<form action="{% url 'todolist:login' %}" method="post">
				{% csrf_token %}
				<div class="mb-3">
					<label for="username">Username</label>
					<input type="text" class="form-control" id="username" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="password">Password</label>
					<input type="password" class="form-control" id="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>
				
				<div class="text-center">
					<input type="submit" value="Login" class="btn btn-success">
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

<!-- {% if is_user_authenticated == False %}
	<h1>Something went Wrong</h1>
	<p>Please contact your administrator or reset your password</p>
	<a href="{% url 'todolist:index' %}">Back to index page</a>
{% endif %} -->

activity/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Register</h1>

				<form action="{% url 'todolist:register' %}" method="post">
					{% csrf_token %}
					<div class="mb-3">
						<label for="username">Username:</label>
						<input type="text" class="form-control" id="username" name="username" value="{{ username }}"
							maxlength="20" required>
					</div>

					<div class="mb-3">
						<label for="first_name">First Name:</label>
						<input type="text" class="form-control" id="first_name" name="first_name" value="{{ first_name }}"
							maxlength="20" required>
					</div>

					<div class="mb-3">
						<label for="last_name">Last Name:</label>
						<input type="text" class="form-control" id="last_name" name="last_name" value="{{ last_name }}"
							maxlength="20" required>
					</div>

					<div class="mb-3">
						<label for="email">Email:</label>
						<input type="email" class="form-control" id="email" name="email" value="{{ email }}"
							maxlength="20" required>
					</div>

					<div class="mb-3">
						<label for="password">Password:</label>
						<input type="password" class="form-control" id="password" name="password" value="{{ password }}"
							maxlength="20" required>
					</div>

					<div class="mb-3">
						<label for="confirm_password">Confirm Password:</label>
						<input type="password" class="form-control" id="confirm_password" name="confirm_password" value="{{ confirm_password }}"
							maxlength="20" required>
					</div>

					<div class="text-center">
						<input type="submit" value="Register" class="btn btn-success">
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

activity/todolist/templates/todolist/todoitem.html
<h1>{{task_name}}</h1>
<h3>Description</h3>
<p>{{description}}</p>
<h3>Status</h3>
<p>{{status}}</p>
<a href="{% url 'todolist:index' %}">Back to index page.</a>

activity/todolist/templates/todolist/update_profile.html
{% extends 'base.html' %}

{% block title %}Update User{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <h1 class="text-center my-3">Update User Information</h1>
                {% if error == True %}
                    <p class="text-danger">User not found</p>
                {% endif %}

                <form action="{% url 'todolist:update_profile' %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="first_name">First Name:</label>
                        <input type="text" class="form-control" id="first_name" name="first_name" value="{{ first_name }}" maxlength="20" required>
                    </div>
    
                    <div class="mb-3">
                        <label for="last_name">Last Name:</label>
                        <input type="text" class="form-control" id="last_name" name="last_name" value="{{ last_name }}" maxlength="20" required></input>
                    </div>
    
                    <div class="mb-3">
                        <label for="password">Password:</label>
                        <input type="password" class="form-control" id="password" name="password" value="{{ password }}" maxlength="20" required>
                    </div>
                    
                    <div class="text-center">
                        <input type="submit" value="Update User" class="btn btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

activity/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <h1 class="text-center my-3">Update Task</h1>
                {% if error == True %}
                    <p class="text-danger">Task not found</p>
                {% endif %}

                <form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="task_name">Task Name:</label>
                        <input type="text" class="form-control" id="task_name" name="task_name" value="{{ task_name }}" maxlength="50" required>
                    </div>
    
                    <div class="mb-3">
                        <label for="description">Description</label>
                        <textarea type="text" class="form-control" id="description" name="description" value="{{ description }}" required></textarea>
                    </div>
    
                    <div class="mb-3">
                        <label for="status">Description</label>
                        <input type="text" class="form-control" id="status" name="status" value="{{ status }}" maxlength="50" required>
                    </div>
                    
                    <div class="text-center">
                        <input type="submit" value="Update Task" class="btn btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}